apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-get-task-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-get-task-api
  template:
    metadata:
      labels:
        app: todo-get-task-api
    spec:
      containers:
      - name: todo-get-task-api
        image: acr5aks.azurecr.io/todo-add-tasks-api:v4
        ports:
        - containerPort: 8000
